//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int MusteriID { get; set; }
        public string Musadi { get; set; }
        public string MusSoyadi { get; set; }
        public Nullable<int> OdaNo { get; set; }
        public Nullable<System.DateTime> gTarih { get; set; }
        public string telefon { get; set; }
        public Nullable<decimal> hesap { get; set; }
        public Nullable<System.DateTime> CTarih { get; set; }
    
        public virtual Odalar Odalar { get; set; }
    }
}
