//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odalar()
        {
            this.Musteriler = new HashSet<Musteriler>();
        }
    
        public int OdaNo { get; set; }
        public string YatakSayisi { get; set; }
        public string BulunduguKat { get; set; }
        public Nullable<bool> BalkonDurumu { get; set; }
        public Nullable<decimal> OdaGunlukTutar { get; set; }
        public Nullable<bool> OdaDolulukDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteriler> Musteriler { get; set; }
    }
}
