//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int PersonelNo { get; set; }
        public string PersonelAdi { get; set; }
        public string PersonelSoyadi { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelMail { get; set; }
        public string PersonelBolum { get; set; }
        public Nullable<int> P_KulanndıgıIzın { get; set; }
        public Nullable<decimal> PersonelMaas { get; set; }
    }
}
