//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stokDurumu
    {
        public int urunID { get; set; }
        public Nullable<int> urunGno { get; set; }
        public string urunAdi { get; set; }
        public string urunBirimi { get; set; }
        public Nullable<int> urunAdet { get; set; }
        public string urunDurumMesaj { get; set; }
        public Nullable<bool> urunVarmiYokmu { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
    
        public virtual urunGrup urunGrup { get; set; }
    }
}
