//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yekili_Kisiler
    {
        public int YoneticiID { get; set; }
        public string YetkiliAdi { get; set; }
        public string YetkiliKadi { get; set; }
        public string YetkiliSifre { get; set; }
    }
}
