//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YılmazHotelEntities : DbContext
    {
        public YılmazHotelEntities()
            : base("name=YılmazHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Yonetim_kisiler> Yonetim_kisiler { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Odalar> Odalar { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<stokDurumu> stokDurumu { get; set; }
        public virtual DbSet<urunGrup> urunGrup { get; set; }
        public virtual DbSet<Yekili_Kisiler> Yekili_Kisiler { get; set; }
    }
}
